### ISSUE TITLE
Support for official HA Integration

### ISSUE THREAD

**Issue by northpower25** [osks/hass-gardena-smart-system#20]
Hi sorry if this is the wrong place, but what can we do/help as community that this integration become the status of an official HA Integration? Is there are an pull request in place on the HA side for what we can vote or other ways of support?

**Comment by osks** [comment]
My goal is also to get an official integration that supports the Gardena Smart devices, but there are some behavior and bugs to work out before I think it's time making an attempt at that.

The PR that @grm did some months ago (https://github.com/home-assistant/core/pull/27690) had some issues and it ended up being closed with a comment about starting with a PR that only adds one platform (i.e. sensor/switch/vacuum). My take from that is that, when it's time, we should start with making a PR that only adds sensors. And when we get that accepted, we can add switches and vacuums (mowers).

Since we're moving the repository, I'm closing this issue as there is no action to take right now.
