### ISSUE TITLE
Battery sensor: not added as sensor

### ISSUE THREAD

**Issue by wijnandtop** [osks/hass-gardena-smart-system#4]
Battery sensors are added as the type of their "parent".
So for the mower the battery sensor is added as a vacuum.
Battery sensor for a switch is added as a switch.

Probably the sensors should be added from the sensor.py, will try to make a PR.

**Comment by osks** [comment]
You're right, I missed that. I guess I only looked at the battery level sensor for my Gardena sensor, and that is correct because that is a sensor. When I look now I have an entity called "switch.water_control_battery_level", which is obviously wrong.

I'm happy for a PR, but if you don't want to I can fix.
