### ISSUE TITLE
Serial missing

### ISSUE THREAD

**Issue by thecem** [osks/hass-gardena-smart-system#8]
The serial number is missing in the devices, is there a possibility to add them?

Thanks a lot for the Intergration!

**Comment by osks** [comment]
In @grm's PR to get his integration into Home Assistant, they commented on having the serial in device_state_attributes, which is why I removed it from there.
https://github.com/home-assistant/core/pull/27690#discussion_r363790836

My goal with this is to get an official integration (sometime in the future), so I don't want to add anything that goes against Home Assistant's guidelines.

I looked into the Home Assistant docs and I can't find a place where to add device (or entity) information that isn't about the state. The device registry only holds manufacturer, model and sw_version, and I haven't found anything relevant for entities. That the serial is part of the unique_id isn't exposed in the GUI.

**Comment by thecem** [comment]
@grm have used `serial: xx.xxx.xxxxx`

maybe the description is here:
Device properties
https://developers.home-assistant.io/docs/device_registry_index/
seems to be `identifiers: xyz0003741`

**Comment by osks** [comment]
The devices that the integration creates already have the `identifiers` property set and is using the serial for that. Unfortunately that is not something that Home Assistant shows to the user, it's just used internally. This is for example how the code currently looks for the GardenaSmartWaterControl:

```
    @property
    def device_info(self):
        return {
            "identifiers": {
                # Serial numbers are unique identifiers within a specific domain
                (DOMAIN, self._device.serial)
            },
            "name": self._device.name,
            "manufacturer": "Gardena",
            "model": self._device.model_type,
        }
```

And as you've noticed, the serial is not shown in the GUI even with this.

**Comment by osks** [comment]
I asked about this on Discord. Didn't get any official answer, but the answer I got indicates that there is currently no suitable attribute in the device registry for a serial.

We could put in sw_version for now, but that will probably not be OK in a official integration. If sw_version can hold an arbitrary string it could be clear that it's a serial and not software version, then I might be think it's okay for now.

**Comment by osks** [comment]
Please continue in the new repository: py-smart-gardena/hass-gardena-smart-system#1
